# config/packages/easy_admin.yaml
easy_admin:
    entities:
        ProductPhoto:
            # ...
            list:
                fields:
                    - { property: 'photo', template: 'product/new.html.twig' }
                    
